version: "3.5"

services:
  webserver:
    image: vjcspy/ebs-docker-php-nginx:7.4-prod
    container_name: "${STACK_NAME}-web"
    domainname: "${STACK_NAME}-web"
    hostname: "${STACK_NAME}-web"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ebs-docker-network
    volumes:
      - MGT_FOLDER:/app
      - ./config/nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    env_file: .env
  mysql:
    image: mysql:5.7
    container_name: "${STACK_NAME}-db"
    domainname: "${STACK_NAME}-db"
    hostname: "${STACK_NAME}-db"
    ports:
      - "3306:3306"
    networks:
      - ebs-docker-network
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
      - ./docker_data/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env
networks:
  ebs-docker-network:
